#!/usr/bin/env python3
# Config generator for the full-frame video sim (tb_video2.v). Derives every per-layer control
# input (tile8/bank/scrx/scry, enables, deco32 priority) for a captured MAME frame from the real
# deco16 control regs — the SAME formulas as ref_render.py / gen_layer.py (no hardcoding, no drift)
# — and emits ver/gfx/video_cfg.vh (the per-PF config + the file paths the tb's behavioral RAMs/ROMs
# load + the sprite-gfx memory sizes). The golden RGB (cm_rgb.hex) comes from ref_render.py.
#   usage: gen_video.py <frame> [pri]      (pri default 1: the f1800 0x150000 tap is clobbered)
import os, sys
frame = int(sys.argv[1]) if len(sys.argv)>1 else 1800
PRI   = int(sys.argv[2]) if len(sys.argv)>2 else 1
d     = os.path.dirname(os.path.abspath(__file__))
caps  = "/path/to/nightslashers/mame-dump/caps"

def hexf(n): return [int(l,16) for l in open(os.path.join(caps,"f%04d_%s.hex"%(frame,n))) if l.strip() and l[0] not in '/@']
c12=hexf("ctl12"); c34=hexf("ctl34"); g=lambda L,i:(L[i]&0xffff) if i<len(L) else 0

# per-PF config (doc/mame_deco32.c get_pfN_tile_info + VIDEO_START/UPDATE(nslasher))
pf1 = dict(tile8=1, bank=0,                 scrx=g(c12,1)&0x1ff, scry=g(c12,2)&0xff)
pf2 = dict(tile8=0, bank=(g(c12,7)>>12)&3,  scrx=g(c12,3)&0x3ff, scry=g(c12,4)&0x1ff)
pf3 = dict(tile8=0, bank=(g(c34,7)>> 4)&3,  scrx=g(c34,1)&0x3ff, scry=g(c34,2)&0x1ff)
pf4 = dict(tile8=0, bank=(g(c34,7)>>12)&3,  scrx=g(c34,3)&0x3ff, scry=g(c34,4)&0x1ff)
en1 = 1 if (g(c12,5)&0x0080) else 0
en2 = 1 if (g(c12,5)&0x8000) else 0
en3 = 1 if (g(c34,5)&0x0080) else 0
en4 = 1 if (g(c34,5)&0x8000) else 0

# sprite-gfx memory sizes (must cover the highest reshuffled half-row addr = max_tile*32+31)
def used_max(name):
    spr=hexf(name); s=0
    for offs in range(0,0x400,4):
        y=spr[offs]&0xffff; code=spr[offs+1]&0xffff; multi=(1<<((y&0x600)>>9))-1
        base=code & ~multi
        for k in range(multi+1): s=max(s, base+k)
    return s
memw0 = used_max("spr0")*32 + 32
memw1 = used_max("spr1")*32 + 32

P = lambda f: os.path.join(caps if f.startswith("f") else d, f).replace("\\","/")
with open(os.path.join(d,"video_cfg.vh"),'w') as f:
    f.write("// auto-generated by gen_video.py (frame %d)\n"%frame)
    for nm,p in (("PF1",pf1),("PF2",pf2),("PF3",pf3),("PF4",pf4)):
        f.write("`define %s_TILE8 1'd%d\n`define %s_BANK 2'd%d\n`define %s_SCRX 10'd%d\n`define %s_SCRY 9'd%d\n"%(
            nm,p["tile8"], nm,p["bank"], nm,p["scrx"], nm,p["scry"]))
    f.write("`define V_EN1 1'b%d\n`define V_EN2 1'b%d\n`define V_EN3 1'b%d\n`define V_EN4 1'b%d\n`define V_PRI 2'd%d\n"%(en1,en2,en3,en4,PRI&3))
    f.write("`define SPR0_MEMW %d\n`define SPR1_MEMW %d\n"%(memw0,memw1))
    f.write('`define PF1FILE "%s"\n'%P("f%04d_pf1.hex"%frame))
    f.write('`define PF2FILE "%s"\n'%P("f%04d_pf2.hex"%frame))
    f.write('`define PF3FILE "%s"\n'%P("f%04d_pf3.hex"%frame))
    f.write('`define PF4FILE "%s"\n'%P("f%04d_pf4.hex"%frame))
    f.write('`define SPR0FILE "%s"\n'%P("f%04d_spr0.hex"%frame))
    f.write('`define SPR1FILE "%s"\n'%P("f%04d_spr1.hex"%frame))
    f.write('`define CTL12FILE "%s"\n'%P("f%04d_ctl12.hex"%frame))
    f.write('`define CTL34FILE "%s"\n'%P("f%04d_ctl34.hex"%frame))
    f.write('`define GFX1C8FILE "%s"\n'%P("gfx1_chars8.hex"))
    f.write('`define GFX1T16FILE "%s"\n'%P("gfx1_tiles16.hex"))
    f.write('`define GFX2T16FILE "%s"\n'%P("gfx2_tiles16.hex"))
    f.write('`define GFX3SPRFILE "%s"\n'%P("gfx3_spr.hex"))
    f.write('`define GFX4SPRFILE "%s"\n'%P("gfx4_spr.hex"))
    f.write('`define PALFILE "%s"\n'%P("f%04d_pal.hex"%frame))

print("gen_video frame=%d pri=%d"%(frame,PRI))
print("  PF1",pf1,"en",en1); print("  PF2",pf2,"en",en2)
print("  PF3",pf3,"en",en3); print("  PF4",pf4,"en",en4)
print("  spr0_memw=%d spr1_memw=%d -> video_cfg.vh"%(memw0,memw1))
