// jtnslasher_game_sdram.v is automatically generated by JTFRAME
// Do not modify it
// Do not add it to git

`ifndef JTFRAME_COLORW
`define JTFRAME_COLORW 4
`endif

`ifndef JTFRAME_BUTTONS
`define JTFRAME_BUTTONS 2
`endif

module jtnslasher_game_sdram(
    `include "jtframe_common_ports.inc"
    `include "jtframe_mem_ports.inc"
);

/* verilator lint_off WIDTH */
localparam [25:0] BA1_START  =`ifdef JTFRAME_BA1_START  `JTFRAME_BA1_START  `else 26'd0 `endif;
localparam [25:0] BA2_START  =`ifdef JTFRAME_BA2_START  `JTFRAME_BA2_START  `else 26'd0 `endif;
localparam [25:0] BA3_START  =`ifdef JTFRAME_BA3_START  `JTFRAME_BA3_START  `else 26'd0 `endif;
localparam [25:0] PROM_START =`ifdef JTFRAME_PROM_START `JTFRAME_PROM_START `else 26'd0 `endif;
localparam [25:0] HEADER_LEN =`ifdef JTFRAME_HEADER     `JTFRAME_HEADER     `else 26'd0 `endif;
localparam        SDRAMW     =`ifdef JTFRAME_SDRAM_LARGE 24 `else 23 `endif;
/* verilator lint_on WIDTH */


parameter SND_OFFSET = (`SND_START -`JTFRAME_BA1_START)>>1;
parameter PCM1_OFFSET = (`PCM1_START-`JTFRAME_BA1_START)>>1;
parameter PCM2_OFFSET = (`PCM2_START-`JTFRAME_BA1_START)>>1;
parameter GFX2_OFFSET = (`GFX2_START -`JTFRAME_BA2_START)>>1;
parameter GFX4_OFFSET = (`GFX4_START -`JTFRAME_BA2_START)>>1;

// Audio channels 
wire signed [15:0] fm_l, fm_r;
wire signed [13:0] oki1;
wire signed [13:0] oki2;
wire mute;
// Additional ports
wire [15:0] main_dout;
wire [1:0] dsn;

// BRAM buses
// SDRAM buses

wire [16:1] ram_addr;
wire [15:0] ram_data;
wire        ram_cs, ram_ok;
wire        ram_we;
wire [15:0] ram_din;
wire [ 1:0] ram_dsn;

wire [19:2] main_addr;
wire [31:0] main_data;
wire        main_cs, main_ok;
wire [15:0] snd_addr;
wire [ 7:0] snd_data;
wire        snd_cs, snd_ok;
wire [18:0] oki1_addr;
wire [ 7:0] oki1_data;
wire        oki1_cs, oki1_ok;
wire [18:0] oki2_addr;
wire [ 7:0] oki2_data;
wire        oki2_cs, oki2_ok;
wire [20:1] gfx1a_addr;
wire [15:0] gfx1a_data;
wire        gfx1a_cs, gfx1a_ok;
wire [20:1] gfx1b_addr;
wire [15:0] gfx1b_data;
wire        gfx1b_cs, gfx1b_ok;
wire [20:1] gfx2a_addr;
wire [15:0] gfx2a_data;
wire        gfx2a_cs, gfx2a_ok;
wire [20:1] gfx2b_addr;
wire [15:0] gfx2b_data;
wire        gfx2b_cs, gfx2b_ok;
wire [19:2] obj1_addr;
wire [31:0] obj1_data;
wire        obj1_cs, obj1_ok;
wire [23:2] obj0_addr;
wire [31:0] obj0_data;
wire        obj0_cs, obj0_ok;
wire        prom_we, header;
wire [SDRAMW-2:0] raw_addr, post_addr;
wire [SDRAMW-2:0] ioctl_prog_addr   = ioctl_addr[SDRAMW-2:0];
wire [25:0] pre_addr, dwnld_addr, ioctl_addr_noheader;
wire [ 7:0] post_data;
wire [15:0] raw_data;
wire [ 7:0] pcb_id;
wire        pass_io;
// Clock enable signals
wire cen_arm; 
wire cen_fm; 
wire cen_fm2; 
wire cen_oki2; 
wire cen_oki1; 
wire gfx4_en, gfx8_en, gfx16_en, gfx16b_en, gfx16c_en, ioctl_dwn;

assign pass_io = header | ioctl_ram;
assign ioctl_addr_noheader = `ifdef JTFRAME_HEADER header ? ioctl_addr : ioctl_addr - HEADER_LEN `else ioctl_addr `endif ;
`ifdef JTFRAME_SDRAM_CACHE
assign burst_addr = { (SDRAMW-1){1'b0} };
assign burst_ba   = 2'd0;
assign burst_rd   = 1'b0;
assign burst_wr   = 1'b0;
assign burst_din  = 16'd0;
`endif

wire rst_h, rst24_h, rst48_h, hold_rst;

/* verilator tracing_off */
jtframe_rsthold u_hold(
    .rst    ( rst       ),
    .clk    ( clk       ),
    .hold   ( hold_rst  ),
    .rst_h  ( rst_h     ),
    .rst24  ( rst24     ),
    .clk24  ( clk24     ),
    .rst24_h( rst24_h   )
`ifdef JTFRAME_CLK48 ,
    .rst48  ( rst48     ),
    .clk48  ( clk48     ),
    .rst48_h( rst48_h   )
`endif
);
/* verilator tracing_on */
jtnslasher_game u_game(
    .rst        ( rst_h     ),
    .clk        ( clk       ),
    .rst24      ( rst24_h   ),
    .clk24      ( clk24     ),
`ifdef JTFRAME_CLK48
    .rst48      ( rst48_h   ),
    .clk48      ( clk48     ),
`endif
    .rst96      ( rst96     ),
    .clk96      ( clk96     ),
    // Audio channels
    .fm_l   ( fm_l    ),
    .fm_r   ( fm_r    ),.oki1     ( oki1      ),.oki2     ( oki2      ),
    
    .snd_en         ( snd_en        ),
    .snd_vol        ( snd_vol       ),
    .cen_arm    ( cen_arm    ), 
    .cen_fm    ( cen_fm    ), 
    .cen_fm2    ( cen_fm2    ), 
    .cen_oki2    ( cen_oki2    ), 
    .cen_oki1    ( cen_oki1    ), 

    .pxl2_cen       ( pxl2_cen      ),
    .pxl_cen        ( pxl_cen       ),
    .red            ( red           ),
    .green          ( green         ),
    .blue           ( blue          ),
    .LHBL           ( LHBL          ),
    .LVBL           ( LVBL          ),
    .HS             ( HS            ),
    .VS             ( VS            ),
    // cabinet I/O
    .cab_1p   ( cab_1p  ),
    .coin     ( coin    ),
    .joystick1    ( joystick1        ), .joystick2    ( joystick2        ),
    .joystick3    ( joystick3        ), .joystick4    ( joystick4        ), `ifdef JTFRAME_MOUSE
    .mouse_1p     ( mouse_1p         ), .mouse_2p     ( mouse_2p         ), .mouse_strobe ( mouse_strobe ), `endif `ifdef JTFRAME_LIGHTGUN
    .gun_1p_x     ( gun_1p_x         ), .gun_1p_y     ( gun_1p_y         ),
    .gun_2p_x     ( gun_2p_x         ), .gun_2p_y     ( gun_2p_y         ), `endif `ifdef JTFRAME_SPINNER
    .spinner_1p   ( spinner_1p       ), .spinner_2p   ( spinner_2p       ), `endif
    .joyana_l1    ( joyana_l1        ), .joyana_l2    ( joyana_l2        ),
    .joyana_l3    ( joyana_l3        ), .joyana_l4    ( joyana_l4        ),
    .joyana_r1    ( joyana_r1        ), .joyana_r2    ( joyana_r2        ),
    .joyana_r3    ( joyana_r3        ), .joyana_r4    ( joyana_r4        ),
    .dial_x       ( dial_x           ), .dial_y       ( dial_y           ),
    // DIP switches
    .status         ( status        ),
    .dipsw          ( dipsw         ),
    .service        ( service       ),
    .tilt           ( tilt          ),
    .dip_pause      ( dip_pause     ),
    .dip_flip       ( dip_flip      ),
    .dip_test       ( dip_test      ),
    .dip_fxlevel    ( dip_fxlevel   ),
    // Ports declared in mem.yaml
    .main_dout   ( main_dout ),
    .dsn   ( dsn ),
    // Memory interface - SDRAM
    .ram_addr ( ram_addr ),
    .ram_cs   ( ram_cs   ),
    .ram_ok   ( ram_ok   ),
    .ram_data ( ram_data ),
    .ram_we   ( ram_we   ),
    
    
    
    .main_addr ( main_addr ),
    .main_cs   ( main_cs   ),
    .main_ok   ( main_ok   ),
    .main_data ( main_data ),
    
    .snd_addr ( snd_addr ),
    .snd_cs   ( snd_cs   ),
    .snd_ok   ( snd_ok   ),
    .snd_data ( snd_data ),
    
    .oki1_addr ( oki1_addr ),
    .oki1_cs   ( oki1_cs   ),
    .oki1_ok   ( oki1_ok   ),
    .oki1_data ( oki1_data ),
    
    .oki2_addr ( oki2_addr ),
    .oki2_cs   ( oki2_cs   ),
    .oki2_ok   ( oki2_ok   ),
    .oki2_data ( oki2_data ),
    
    .gfx1a_addr ( gfx1a_addr ),
    .gfx1a_cs   ( gfx1a_cs   ),
    .gfx1a_ok   ( gfx1a_ok   ),
    .gfx1a_data ( gfx1a_data ),
    
    .gfx1b_addr ( gfx1b_addr ),
    .gfx1b_cs   ( gfx1b_cs   ),
    .gfx1b_ok   ( gfx1b_ok   ),
    .gfx1b_data ( gfx1b_data ),
    
    .gfx2a_addr ( gfx2a_addr ),
    .gfx2a_cs   ( gfx2a_cs   ),
    .gfx2a_ok   ( gfx2a_ok   ),
    .gfx2a_data ( gfx2a_data ),
    
    .gfx2b_addr ( gfx2b_addr ),
    .gfx2b_cs   ( gfx2b_cs   ),
    .gfx2b_ok   ( gfx2b_ok   ),
    .gfx2b_data ( gfx2b_data ),
    
    .obj1_addr ( obj1_addr ),
    .obj1_cs   ( obj1_cs   ),
    .obj1_ok   ( obj1_ok   ),
    .obj1_data ( obj1_data ),
    
    .obj0_addr ( obj0_addr ),
    .obj0_cs   ( obj0_cs   ),
    .obj0_ok   ( obj0_ok   ),
    .obj0_data ( obj0_data ),
    
    // Memory interface - BRAM

`ifdef JTFRAME_SRAM
    // SRAM
    .sram_addr  ( sram_addr     ),
    .sram_din   ( sram_din      ),
    .sram_dout  ( sram_dout     ),
    .sram_wen   ( sram_wen      ),
    .sram_dsn   ( sram_dsn      ),
    .sram_ok    ( sram_ok       ),
`endif

`ifdef JTFRAME_SAVEGAME
    // Save/Load
    .sav_change ( sav_change    ),
    .sav_wait   ( sav_wait      ),
    .sav_done   ( sav_done      ),
    .sav_wr     ( sav_wr        ),
    .sav_ack    ( sav_ack       ),
    .sav_din    ( sav_din       ),
    .sav_dout   ( sav_dout      ),
    .sav_addr   ( sav_addr      ),
`endif
    // PROM writting
    .ioctl_addr   ( pass_io ? ioctl_addr       : ioctl_addr_noheader  ),
    .prog_addr    ( pass_io ? ioctl_prog_addr : raw_addr      ),
    .prog_data    ( pass_io ? ioctl_dout       : raw_data[7:0] ),
    .prog_we      ( pass_io ? ioctl_wr         : prog_we       ),
    .prog_ba      ( prog_ba        ), // prog_ba supplied in case it helps re-mapping addresses
    .prom_we      ( pass_io ? 1'b0 : prom_we ),
    // SDRAM address mapper during downloading
    .post_addr    ( post_addr      ),
    .post_data    ( post_data      ),
`ifdef JTFRAME_HEADER
    .header       ( header         ),
`endif
`ifdef JTFRAME_IOCTL_RD
    .ioctl_din    ( ioctl_din      ),
    .ioctl_dout   ( ioctl_dout     ),
    .ioctl_wr     ( ioctl_wr       ), `endif
    .ioctl_ram    ( ioctl_ram      ),
    .ioctl_cart   ( ioctl_cart     ),
    // Debug
    .debug_bus    ( debug_bus      ),
    .debug_view   ( debug_view     ),
`ifdef JTFRAME_STATUS
    .st_addr      ( st_addr        ),
    .st_dout      ( st_dout        ),
`endif
`ifdef JTFRAME_LF_BUFFER
    .game_vrender( game_vrender  ),
    .game_hdump  ( game_hdump    ),
    .ln_addr     ( ln_addr       ),
    .ln_data     ( ln_data       ),
    .ln_done     ( ln_done       ),
    .ln_hs       ( ln_hs         ),
    .ln_dout     ( ln_dout       ),
    .ln_pxl      ( ln_pxl        ),
    .ln_v        ( ln_v          ),
    .ln_vs       ( ln_vs         ),
    .ln_lvbl     ( ln_lvbl       ),
    .ln_we       ( ln_we         ),
`endif
    .gfx_en      ( gfx_en        )
);
/* verilator tracing_off */
assign dwnld_busy = ioctl_rom | prom_we; // prom_we is really just for sims
assign dwnld_addr = ioctl_addr;
assign prog_addr = post_addr;
assign prog_data = {2{post_data}};
assign gfx4_en   = 0;
assign gfx8_en   = 0;
assign gfx16_en  = 0;
assign gfx16b_en = 0;
assign gfx16c_en = 0;
assign ioctl_dwn = ioctl_rom | ioctl_cart;
`ifdef VERILATOR_KEEP_SDRAM /* verilator tracing_on */ `else /* verilator tracing_off */ `endif
jtframe_dwnld #(
    .SDRAMW     ( SDRAMW       ),
`ifdef JTFRAME_HEADER
    .HEADER    ( `JTFRAME_HEADER   ),
`endif
`ifdef JTFRAME_BA1_START
    .BA1_START ( BA1_START ),
`endif
`ifdef JTFRAME_BA2_START
    .BA2_START ( BA2_START ),
`endif
`ifdef JTFRAME_BA3_START
    .BA3_START ( BA3_START ),
`endif
`ifdef JTFRAME_PROM_START
    .PROM_START( PROM_START ),
`endif
    .SWAB      ( 1),
    .GFX8B0    ( 0),
    .GFX16B0   ( 0)
) u_dwnld(
    .clk          ( clk            ),
    .ioctl_rom    ( ioctl_dwn      ),
    .ioctl_addr   ( dwnld_addr     ),
    .ioctl_dout   ( ioctl_dout     ),
    .ioctl_wr     ( ioctl_wr       ),
    .gfx4_en      ( gfx4_en        ),
    .gfx8_en      ( gfx8_en        ),
    .gfx16_en     ( gfx16_en       ),
    .gfx16b_en    ( gfx16b_en      ),
    .gfx16c_en    ( gfx16c_en      ),
    .prog_addr    ( raw_addr       ),
    .prog_data    ( raw_data       ),
    .prog_mask    ( prog_mask      ), // active low
    .prog_we      ( prog_we        ),
    .prog_rd      ( prog_rd        ),
    .prog_ba      ( prog_ba        ),
    .prom_we      ( prom_we        ),
    .header       ( header         ),
    .sdram_ack    ( prog_ack       )
);

jtframe_headerbyte #(.AW(6)) u_pcbid(
    .clk          ( clk            ),
    .header       ( header         ),
    .ioctl_addr   ( ioctl_addr[5:0]),
    .ioctl_dout   ( ioctl_dout     ),
    .ioctl_wr     ( ioctl_wr       ),
    .dout         ( pcb_id         )
);
`ifdef VERILATOR_KEEP_SDRAM /* verilator tracing_on */ `else /* verilator tracing_off */ `endif


jtframe_ram1_1slot #(
    .SDRAMW(SDRAMW-1),
    // ram
    .SLOT0_AW(16),
    .SLOT0_DW(16)
`ifdef JTFRAME_BA0_LEN
`endif
) u_bank0(
    .rst         ( rst        ),
    .clk         ( clk        ),
    
    .slot0_addr  ( ram_addr  ),
    .hold_rst    (  hold_rst  ),
    .slot0_wen   ( ram_we    ),
    .slot0_din   ( main_dout   ),
    .slot0_wrmask( dsn   ),
    .slot0_offset( {(SDRAMW-1){1'b0}} ),
    .slot0_dout  ( ram_data  ),
    .slot0_cs    ( ram_cs    ),
    .slot0_ok    ( ram_ok    ),
    
    // SDRAM controller interface
    .sdram_ack   ( ba_ack[0]  ),
    .sdram_rd    ( ba_rd[0]   ),
    .sdram_addr  ( ba0_addr   ),
    .sdram_wr    ( ba_wr[0]   ),
    .sdram_wrmask( ba0_dsn    ),
    .data_write  ( ba0_din    ),
    .data_dst    ( ba_dst[0]  ),
    .data_rdy    ( ba_rdy[0]  ),
    .data_read   ( data_read  )
);
jtframe_rom_4slots #(
    .SDRAMW(SDRAMW-1),
    // main
    .SLOT0_AW(19),
    .SLOT0_DW(32), 
    // snd
    .SLOT1_OFFSET(SND_OFFSET[SDRAMW-2:0]),
    .SLOT1_AW(16),
    .SLOT1_DW( 8), 
    // oki1
    .SLOT2_OFFSET(PCM1_OFFSET[SDRAMW-2:0]),
    .SLOT2_AW(19),
    .SLOT2_DW( 8), 
    // oki2
    .SLOT3_OFFSET(PCM2_OFFSET[SDRAMW-2:0]),
    .SLOT3_AW(19),
    .SLOT3_DW( 8)
`ifdef JTFRAME_BA1_LEN
    ,.SLOT0_DOUBLE(1)
    ,.SLOT1_DOUBLE(1)
    ,.SLOT2_DOUBLE(1)
    ,.SLOT3_DOUBLE(1)
`endif
) u_bank1(
    .rst         ( rst        ),
    .clk         ( clk        ),
    
    .slot0_addr  ( { main_addr, 1'b0 } ),
    .slot0_dout  ( main_data  ),
    .slot0_cs    ( main_cs    ),
    .slot0_ok    ( main_ok    ),
    
    .slot1_addr  ( snd_addr  ),
    .slot1_dout  ( snd_data  ),
    .slot1_cs    ( snd_cs    ),
    .slot1_ok    ( snd_ok    ),
    
    .slot2_addr  ( oki1_addr  ),
    .slot2_dout  ( oki1_data  ),
    .slot2_cs    ( oki1_cs    ),
    .slot2_ok    ( oki1_ok    ),
    
    .slot3_addr  ( oki2_addr  ),
    .slot3_dout  ( oki2_data  ),
    .slot3_cs    ( oki2_cs    ),
    .slot3_ok    ( oki2_ok    ),
    
    // SDRAM controller interface
    .sdram_ack   ( ba_ack[1]  ),
    .sdram_rd    ( ba_rd[1]   ),
    .sdram_addr  ( ba1_addr   ),
    .data_dst    ( ba_dst[1]  ),
    .data_rdy    ( ba_rdy[1]  ),
    .data_read   ( data_read  )
);
assign ba_wr[1] = 0;
assign ba1_din  = 0;
assign ba1_dsn  = 3;
jtframe_rom_5slots #(
    .SDRAMW(SDRAMW-1),
    // gfx1a
    .SLOT0_AW(20),
    .SLOT0_DW(16), 
    // gfx1b
    .SLOT1_AW(20),
    .SLOT1_DW(16), 
    // gfx2a
    .SLOT2_OFFSET(GFX2_OFFSET[SDRAMW-2:0]),
    .SLOT2_AW(20),
    .SLOT2_DW(16), 
    // gfx2b
    .SLOT3_OFFSET(GFX2_OFFSET[SDRAMW-2:0]),
    .SLOT3_AW(20),
    .SLOT3_DW(16), 
    // obj1
    .SLOT4_OFFSET(GFX4_OFFSET[SDRAMW-2:0]),
    .SLOT4_AW(19),
    .SLOT4_DW(32)
`ifdef JTFRAME_BA2_LEN
    ,.SLOT0_DOUBLE(1)
    ,.SLOT1_DOUBLE(1)
    ,.SLOT2_DOUBLE(1)
    ,.SLOT3_DOUBLE(1)
    ,.SLOT4_DOUBLE(1)
`endif
) u_bank2(
    .rst         ( rst        ),
    .clk         ( clk        ),
    
    .slot0_addr  ( gfx1a_addr  ),
    .slot0_dout  ( gfx1a_data  ),
    .slot0_cs    ( gfx1a_cs    ),
    .slot0_ok    ( gfx1a_ok    ),
    
    .slot1_addr  ( gfx1b_addr  ),
    .slot1_dout  ( gfx1b_data  ),
    .slot1_cs    ( gfx1b_cs    ),
    .slot1_ok    ( gfx1b_ok    ),
    
    .slot2_addr  ( gfx2a_addr  ),
    .slot2_dout  ( gfx2a_data  ),
    .slot2_cs    ( gfx2a_cs    ),
    .slot2_ok    ( gfx2a_ok    ),
    
    .slot3_addr  ( gfx2b_addr  ),
    .slot3_dout  ( gfx2b_data  ),
    .slot3_cs    ( gfx2b_cs    ),
    .slot3_ok    ( gfx2b_ok    ),
    
    .slot4_addr  ( { obj1_addr, 1'b0 } ),
    .slot4_dout  ( obj1_data  ),
    .slot4_cs    ( obj1_cs    ),
    .slot4_ok    ( obj1_ok    ),
    
    // SDRAM controller interface
    .sdram_ack   ( ba_ack[2]  ),
    .sdram_rd    ( ba_rd[2]   ),
    .sdram_addr  ( ba2_addr   ),
    .data_dst    ( ba_dst[2]  ),
    .data_rdy    ( ba_rdy[2]  ),
    .data_read   ( data_read  )
);
assign ba_wr[2] = 0;
assign ba2_din  = 0;
assign ba2_dsn  = 3;
jtframe_rom_1slot #(
    .SDRAMW(SDRAMW-1),
    // obj0
    .SLOT0_AW(23),
    .SLOT0_DW(32)
`ifdef JTFRAME_BA3_LEN
    ,.SLOT0_DOUBLE(1)
`endif
) u_bank3(
    .rst         ( rst        ),
    .clk         ( clk        ),
    
    .slot0_addr  ( { obj0_addr, 1'b0 } ),
    .slot0_dout  ( obj0_data  ),
    .slot0_cs    ( obj0_cs    ),
    .slot0_ok    ( obj0_ok    ),
    
    // SDRAM controller interface
    .sdram_ack   ( ba_ack[3]  ),
    .sdram_rd    ( ba_rd[3]   ),
    .sdram_addr  ( ba3_addr   ),
    .data_dst    ( ba_dst[3]  ),
    .data_rdy    ( ba_rdy[3]  ),
    .data_read   ( data_read  )
);
assign ba_wr[3] = 0;
assign ba3_din  = 0;
assign ba3_dsn  = 3;

`ifdef JTFRAME_PROM_START
localparam JTFRAME_PROM_START=`JTFRAME_PROM_START;
`endif



// Clock enable generation
// 7080500 = 48000000*7753/52559 Hz from clk
`ifdef VERILATOR_KEEP_CEN /* verilator tracing_on */ `else /* verilator tracing_off */ `endif
jtframe_gated_cen #(.W(1),.NUM(7753),.DEN(52559),.MFREQ(48000)) u_cen0_clk(
    .rst    ( rst          ),
    .clk    ( clk ),
    .busy   ( 1'b0    ),
    .cen    ( { cen_arm } ),
    .fave   (              ),
    .fworst (              )
); /* verilator tracing_off */

// 3580000 = 48000000*179/2400 Hz from clk
`ifdef VERILATOR_KEEP_CEN /* verilator tracing_on */ `else /* verilator tracing_off */ `endif
jtframe_gated_cen #(.W(2),.NUM(179),.DEN(2400),.MFREQ(48000)) u_cen1_clk(
    .rst    ( rst          ),
    .clk    ( clk ),
    .busy   ( (snd_cs & ~snd_ok)    ),
    .cen    ( { cen_fm2, cen_fm } ),
    .fave   (              ),
    .fworst (              )
); /* verilator tracing_off */

// 2014000 = 48000000*1007/24000 Hz from clk
`ifdef VERILATOR_KEEP_CEN /* verilator tracing_on */ `else /* verilator tracing_off */ `endif
jtframe_gated_cen #(.W(1),.NUM(1007),.DEN(24000),.MFREQ(48000)) u_cen2_clk(
    .rst    ( rst          ),
    .clk    ( clk ),
    .busy   ( 1'b0    ),
    .cen    ( { cen_oki2 } ),
    .fave   (              ),
    .fworst (              )
); /* verilator tracing_off */

// 1007000 = 48000000*1007/48000 Hz from clk
`ifdef VERILATOR_KEEP_CEN /* verilator tracing_on */ `else /* verilator tracing_off */ `endif
jtframe_gated_cen #(.W(1),.NUM(1007),.DEN(48000),.MFREQ(48000)) u_cen3_clk(
    .rst    ( rst          ),
    .clk    ( clk ),
    .busy   ( 1'b0    ),
    .cen    ( { cen_oki1 } ),
    .fave   (              ),
    .fworst (              )
); /* verilator tracing_off */

`ifndef NOSOUND
`ifdef VERILATOR_KEEP_AUDIO /* verilator tracing_on */ `else /* verilator tracing_off */ `endif
assign mute=0;

jtframe_rcmix #(
    .W0(16),
    .W1(14),
    .W2(14),
    .STEREO0( 1),
    .STEREO1( 0),
    .STEREO2( 0),
    .STEREO3( 0),
    .STEREO4( 0),
    .STEREO5( 0),
    .DCRM0  ( 0),
    .DCRM1  ( 0),
    .DCRM2  ( 0),
    .DCRM3  ( 0),
    .DCRM4  ( 0),
    .DCRM5  ( 0),
    .STEREO ( 0),
    // Fractional cen for 192kHz
    .FRACW( 9), .FRACN(1), .FRACM(250)
) u_rcmix(
`ifdef JTFRAME_CLK48
    .rst    ( rst48     ),
    .clk    ( clk48     ),
`else
    .rst    ( rst       ),
    .clk    ( clk       ),
`endif
    .mute   ( mute      ),
    .sample ( sample    ),
    .ch_en  ( snd_en    ),
    .gpole  ( 15'h3F66 ),  // 19894 Hz 
    .ch0    ( { fm_l,fm_r } ),
    .ch1    ( oki1 ),
    .ch2    ( oki2 ),
    .ch3    ( 16'd0 ),
    .ch4    ( 16'd0 ),
    .ch5    ( 16'd0 ),
    .p0     ( 30'h0), // 0 Hz, 0 Hz 
    .p1     ( 30'h0), // 0 Hz, 0 Hz 
    .p2     ( 30'h0), // 0 Hz, 0 Hz 
    .p3     ( 30'h0), 
    .p4     ( 30'h0), 
    .p5     ( 30'h0), 
    .g0     ( 8'h29 ), // 0.32  fm
    .g1     ( 8'h80 ), // 1.00  oki1
    .g2     ( 8'h1E ), // 0.23  oki2
    .g3     ( 8'h00 ), // 0.00 
    .g4     ( 8'h00 ), // 0.00 
    .g5     ( 8'h00 ), // 0.00 
    .gain   ( snd_vol   ),
    .mixed  ( snd       ),
    .peak   ( snd_peak  ),
    .vu     ( snd_vu    )
);
`else
assign snd=0;
assign snd_vu   = 0;
assign snd_peak = 0;
wire ncs;
jtframe_frac_cen #(.WC(9)) u_cen192(
    .clk    ( clk       ),
    .n      ( 1 ),
    .m      ( 250 ),
    .cen    ( {  ncs,sample }  ), // sample is always 192 kHz
    .cenb   (                  )
);
`endif
endmodule
