#!/usr/bin/env python3
# Generate the on-cab debugger golden table: for a probe set of ARM words, the
# golden RAW (encrypted SDRAM word) and golden DEC (deco156-decrypted word) that
# the HW *should* read. The overlay shows all 32 bits AND classifies OK/SWAP, so
# nothing is inferred. Emits hdl/dbg_golden.vh + a human-readable dump.
import os
D   = os.path.dirname(os.path.abspath(__file__))
ROM = os.environ.get("ROMDIR", os.path.join(D,"..","..","..","..","..","roms"))
a = open(os.path.join(ROM,"ly-00.1f"),"rb").read()
b = open(os.path.join(ROM,"ly-01.2f"),"rb").read()
N = len(a)//2
src = [(a[2*i]|(a[2*i+1]<<8)) | ((b[2*i]|(b[2*i+1]<<8))<<16) for i in range(N)]

addrx=[0xce4a,0x4db2,0xef60,0x5737,0x13dc,0x4bd9,0xa209,0xd996,
       0xa700,0xeca0,0x7529,0x3100,0x33b4,0x6161,0x1eef,0xf5a5]
datax=[(2,0x04400000),(3,0x40000004),(4,0x00048000),(5,0x00000280),(6,0x00200040),
       (7,0x09000000),(8,0x00001100),(9,0x20002000),(10,0x00000022),(11,0x000a0000),
       (12,0x10004000),(13,0x00010400),(14,0x80000010),(15,0x00000009),(16,0x02100000),(17,0x00800800)]
consts=[0xec63197a,0x58a5a55f,0xe3a65f16,0x28d93783]
ords=[[1,4,7,28,22,18,20,9,16,10,30,2,31,24,19,29,6,21,23,11,12,13,5,0,8,26,27,15,14,17,25,3],
      [14,23,28,29,6,24,10,1,5,16,7,2,30,8,18,3,31,22,25,20,17,0,19,27,9,12,21,15,26,13,4,11],
      [19,30,21,4,2,18,15,1,12,25,8,0,24,20,17,23,22,26,28,16,9,27,6,11,31,10,3,13,14,7,29,5],
      [30,6,15,0,31,18,26,22,14,23,19,17,10,8,11,20,1,28,2,4,9,24,25,27,7,21,13,29,5,3,16,12]]
def bitswap32(v,o):
    r=0
    for i,bb in enumerate(o):
        if (v>>bb)&1: r|=1<<(31-i)
    return r
def saddr_of(w):
    addr=(w&0xff0000)|0x92c6
    for i in range(16):
        if w&(1<<i): addr^=addrx[i]
    return addr
def dec_of(w):
    d=src[saddr_of(w)]
    for bit,mask in datax:
        if w&(1<<bit): d^=mask
    c=w&3
    return bitswap32(d^consts[c], ords[c])

# probe set: reset/early-boot code (guaranteed: w=0 reset vector) + the LUT-overrun region
probes = [0x00000,0x00001,0x00002,0x00004,0x00008,0x00010,0x00040,0x00100,
          0x25410,0x25411,0x25412,0x25413,0x25414,0x25415,0x25416,0x25417]
rows=[]
print("idx  arm_word  saddr    golden_raw  golden_dec   (byteswap_raw)")
for k,w in enumerate(probes):
    sa=saddr_of(w); graw=src[sa]; gdec=dec_of(w)
    bsw=((graw&0xff)<<24)|((graw&0xff00)<<8)|((graw>>8)&0xff00)|((graw>>24)&0xff)
    print("%2d  %06X   %06X   %08X    %08X    (%08X)"%(k,w,sa,graw,gdec,bsw))
    rows.append((w,graw,gdec))

vh=["// AUTO-GENERATED by gen_dbg_golden.py -- on-cab debugger golden table. DO NOT EDIT.",
    "localparam DBG_N = %d;"%len(rows)]
def arr(name,width,vals):
    vh.append("wire [%d:0] %s [0:DBG_N-1];"%(width-1,name))
    for i,v in enumerate(vals):
        vh.append("assign %s[%2d] = %d'h%0*X;"%(name,i,width,(width+3)//4,v))
arr("dbg_aw",   18,[r[0] for r in rows])
arr("dbg_graw", 32,[r[1] for r in rows])
arr("dbg_gdec", 32,[r[2] for r in rows])
open(os.path.join(D,"..","..","hdl","dbg_golden.vh"),"w").write("\n".join(vh)+"\n")
print("\nwrote hdl/dbg_golden.vh (%d entries). idx 12 = LUT target arm 0x95050."%len(rows))
